stages:
  - deploy

variables:
  DOCKER_REGISTRY: "https://gitlab.com/nickjabs/devops-demo"

before_script:
  - apt-get update -qy
  - apt-get install -y docker.io docker-compose

deploy:
  stage: deploy
  script:
    - set -e
    - date +"%Y-%m-%d %H:%M:%S"
    - echo "Logging in to Docker registry..."
    - docker login "docker.io" -u $USER_NAME --password-stdin <<<$TOKEN
    - echo "Current directory contents:"
    - ls -al
    - echo "pulling the image..."
    - docker pull kikibuh/pimcore-demo 
    - docker-compose up -d
    - echo "Docker containers status:"
    - docker ps -a
