stages:
  - deploy

variables:
  DOCKER_REGISTRY: "https://gitlab.com/nickjabs/devops-demo"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $DOCKER_REGISTRY

deploy:
  stage: deploy
  script:
    - set -e
    - echo "Pulling the latest code..."
    - git pull origin main
    - echo "Building Docker images..."
    - docker-compose -f docker-compose.yml build
    - echo "Starting containers in the background..."
    - docker-compose -f docker-compose.yml up -d
