stages:
  - deploy

variables:
  DOCKER_REGISTRY: "https://gitlab.com/nickjabs/devops-demo"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $DOCKER_REGISTRY

deploy:
  stage: deploy
  script:
    - chmod +x deploy.sh
    - ./deploy.sh
