name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          echo "Step 1: Building Docker image..."
          docker build -t mypimcoreimage:latest .
          if [ $? -eq 0 ]; then
            echo "Step 1: Built Docker image successfully"
          else
            echo "Error: Step 1 failed - Failed to build Docker image"
            exit 1
          fi

  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Login to Docker Hub
        run: |
          echo "Step 2: Logging in to Docker Hub..."
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          if [ $? -eq 0 ]; then
            echo "Step 2: Logged in to Docker Hub successfully"
          else
            echo "Error: Step 2 failed - Failed to log in to Docker Hub"
            exit 1
          fi

      - name: Tag Docker image
        run: |
          echo "Step 3: Tagging Docker image..."
          docker tag mypimcoreimage:latest ${{ secrets.DOCKERHUB_USERNAME }}/mypimcoreimage:latest
          if [ $? -eq 0 ]; then
            echo "Step 3: Tagged Docker image successfully"
          else
            echo "Error: Step 3 failed - Failed to tag Docker image"
            exit 1
          fi

      - name: Push Docker image
        run: |
          echo "Step 4: Pushing Docker image..."
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mypimcoreimage:latest
          if [ $? -eq 0 ]; then
            echo "Step 4: Pushed Docker image successfully"
          else
            echo "Error: Step 4 failed - Failed to push Docker image"
            exit 1
          fi

      - name: Task complete
        run: echo "Task complete"
